package com.ghostwave.app.crypto

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import android.util.Log
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

private const val TAG = "KeyStoreManager"

private const val ANDROID_KEYSTORE  = "AndroidKeyStore"
private const val AES_GCM_NO_PAD   = "AES/GCM/NoPadding"
private const val GCM_TAG_BITS      = 128   // 16-byte authentication tag
private const val KEY_SIZE_BITS     = 256   // AES-256

/**
 * Wraps Android Keystore operations used throughout GhostWave.
 *
 * Design rationale:
 * - Android Keystore does NOT natively support Curve25519, so Signal's
 *   identity private key cannot be stored there directly.
 * - Instead we keep an AES-256-GCM key in the Keystore (hardware-backed
 *   on API 28+ StrongBox devices, TEE-backed otherwise).
 * - All Signal key material is encrypted with that AES key before it
 *   ever touches disk. The AES key itself is non-extractable.
 * - This matches the approach used by WhatsApp and many Signal forks.
 *
 * Thread safety: all javax.crypto.Cipher instances are created fresh per
 * call — Cipher is NOT thread-safe.
 */
@Singleton
class KeyStoreManager @Inject constructor() {

    private val keyStore: KeyStore =
        KeyStore.getInstance(ANDROID_KEYSTORE).also { it.load(null) }

    // ── Key provisioning ────────────────────────────────────────────────────

    /**
     * Returns the AES-256-GCM secret key at [alias], creating it on first use.
     * The key is permanently bound to this device's Keystore; it cannot be
     * exported or backed up.
     */
    fun getOrCreateAesKey(alias: String): SecretKey {
        if (!keyStore.containsAlias(alias)) {
            createAesKey(alias)
        }
        return (keyStore.getEntry(alias, null) as KeyStore.SecretKeyEntry).secretKey
    }

    private fun createAesKey(alias: String) {
        val purposes = KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        val spec = KeyGenParameterSpec.Builder(alias, purposes)
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(KEY_SIZE_BITS)
            // Require user authentication for the DB key only in Step 17 (app lock).
            // For the Signal identity key we keep it unlocked so background message
            // decryption works even when the screen is off.
            .setUserAuthenticationRequired(false)
            // Prefer StrongBox (discrete security chip) on API 28+ when available.
            // StrongBox operations are slower but provide the strongest isolation guarantee.
            .applyStrongBoxIfAvailable()
            .build()

        KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, ANDROID_KEYSTORE)
            .also { it.init(spec) }
            .generateKey()
    }

    // ── Encrypt / Decrypt ───────────────────────────────────────────────────

    /**
     * Encrypts [plaintext] under the AES-256-GCM Keystore key at [alias].
     *
     * The Cipher generates a fresh random IV on each call — never reuse an IV
     * with the same key. Returns (iv, ciphertext); both must be persisted.
     * The IV is not secret and can be stored alongside the ciphertext.
     *
     * GCM ciphertext includes the 16-byte authentication tag appended by the JCE,
     * so [decrypt] will throw [javax.crypto.AEADBadTagException] on any tampering.
     */
    fun encrypt(alias: String, plaintext: ByteArray): EncryptedBlob {
        val cipher = Cipher.getInstance(AES_GCM_NO_PAD)
        cipher.init(Cipher.ENCRYPT_MODE, getOrCreateAesKey(alias))
        val ciphertext = cipher.doFinal(plaintext)
        val iv         = cipher.iv   // 12-byte GCM IV generated by JCE
        return EncryptedBlob(iv = iv, ciphertext = ciphertext)
    }

    /**
     * Decrypts a blob produced by [encrypt].
     *
     * @throws javax.crypto.AEADBadTagException if the ciphertext was tampered with.
     * @throws java.security.GeneralSecurityException for other Keystore errors.
     */
    fun decrypt(alias: String, blob: EncryptedBlob): ByteArray {
        val cipher = Cipher.getInstance(AES_GCM_NO_PAD)
        val spec   = GCMParameterSpec(GCM_TAG_BITS, blob.iv)
        cipher.init(Cipher.DECRYPT_MODE, getOrCreateAesKey(alias), spec)
        return cipher.doFinal(blob.ciphertext)
    }

    // ── HMAC-SHA256 (promo integrity token) ──────────────────────────────────

    /**
     * Returns an HMAC-SHA256 key at [alias], creating it on first use.
     * Used exclusively for the promo code integrity token.
     */
    fun getOrCreateHmacKey(alias: String): SecretKey {
        if (!keyStore.containsAlias(alias)) {
            val spec = KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY,
            )
                .setDigests(KeyProperties.DIGEST_SHA256)
                .setUserAuthenticationRequired(false)
                .build()
            KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_HMAC_SHA256, ANDROID_KEYSTORE)
                .also { it.init(spec) }
                .generateKey()
        }
        return (keyStore.getEntry(alias, null) as KeyStore.SecretKeyEntry).secretKey
    }

    /**
     * Computes HMAC-SHA256([data]) with the Keystore key at [alias].
     * Returns lowercase hex. Key material never leaves the Keystore.
     */
    fun hmacSha256(alias: String, data: String): String {
        val mac = Mac.getInstance("HmacSHA256")
        mac.init(getOrCreateHmacKey(alias))
        return mac.doFinal(data.toByteArray(Charsets.UTF_8))
            .joinToString("") { "%02x".format(it) }
    }

    /**
     * Constant-time HMAC verification to prevent timing side-channels.
     */
    fun verifyHmac(alias: String, data: String, expectedHex: String): Boolean {
        val actual   = hmacSha256(alias, data)
        val expected = expectedHex.lowercase()
        if (actual.length != expected.length) return false
        var diff = 0
        for (i in actual.indices) diff = diff or (actual[i].code xor expected[i].code)
        return diff == 0
    }

    // ── Hardware attestation ──────────────────────────────────────────────────

    /**
     * Returns true if the key at [alias] resides in hardware (TEE or StrongBox).
     * Shown in Settings > Security > Encryption status card.
     */
    fun isHardwareBacked(alias: String): Boolean {
        val key = keyStore.getKey(alias, null) as? SecretKey ?: return false
        return try {
            val factory = SecretKeyFactory.getInstance(key.algorithm, ANDROID_KEYSTORE)
            val info    = factory.getKeySpec(key, KeyInfo::class.java) as KeyInfo
            info.isInsideSecureHardware
        } catch (e: Exception) {
            Log.w(TAG, "Could not determine hardware backing for $alias", e)
            false
        }
    }

    // ── Key lifecycle ────────────────────────────────────────────────────────

    fun hasKey(alias: String): Boolean = keyStore.containsAlias(alias)

    /**
     * Permanently deletes a Keystore key.
     *
     * Called during "Re-register" (nuclear option in Settings > Security).
     * After this, any data encrypted with this key is permanently unreadable —
     * which is exactly the desired behaviour for forward secrecy on key rotation.
     */
    fun deleteKey(alias: String) {
        if (keyStore.containsAlias(alias)) {
            keyStore.deleteEntry(alias)
        }
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private fun KeyGenParameterSpec.Builder.applyStrongBoxIfAvailable(): KeyGenParameterSpec.Builder {
        // StrongBox available from API 28; check at runtime to avoid hard crash on older devices
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
            try {
                setIsStrongBoxBacked(true)
            } catch (_: Exception) {
                // Device does not have StrongBox — fall back to TEE (still hardware-backed)
            }
        }
        return this
    }
}

/** Pair of (IV, ciphertext) produced by AES-GCM encryption. */
data class EncryptedBlob(
    val iv:         ByteArray,
    val ciphertext: ByteArray,
) {
    // ByteArray equals/hashCode are identity by default; override for value semantics in tests
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other !is EncryptedBlob) return false
        return iv.contentEquals(other.iv) && ciphertext.contentEquals(other.ciphertext)
    }
    override fun hashCode(): Int = 31 * iv.contentHashCode() + ciphertext.contentHashCode()
}
