package com.ghostwave.app.data.model

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * A single message in a 1:1 conversation.
 *
 * Storage model:
 *   The body is stored as PLAINTEXT inside the SQLCipher-encrypted database.
 *   Signal Protocol decrypts the wire ciphertext before the message reaches
 *   this layer. The SQLCipher AES-256 encryption of the DB file itself
 *   provides equivalent at-rest protection, while also enabling full-text
 *   search without exposing plaintext outside the DB.
 *
 * Media flow (IPFS + AES-256-GCM):
 *   1. Sender encrypts file locally → uploads ciphertext to IPFS
 *   2. Sender embeds (mediaIpfsCid, mediaKeyBase64, mediaIvBase64) in a
 *      Signal-encrypted message → sent via data channel
 *   3. Receiver stores these fields here after decrypting the Signal message
 *   4. Receiver fetches ciphertext from IPFS → decrypts using stored key/IV
 */
@Entity(
    tableName = "messages",
    foreignKeys = [
        ForeignKey(
            entity          = Contact::class,
            parentColumns   = ["id"],
            childColumns    = ["contactId"],
            onDelete        = ForeignKey.CASCADE,   // deleting a contact wipes their messages
        ),
    ],
    indices = [
        Index("contactId"),                         // conversation query
        Index("timestamp"),                         // chronological ordering
        Index("status"),                            // pending-message queue lookup
        Index("expiresAt"),                         // disappearing-message sweeper
    ],
)
data class Message(
    @PrimaryKey val id: String,                     // UUID generated by sender
    val contactId: String,                          // FK → Contact.id
    val senderGwId: String,                         // GW-ID of the sender
    val body: String,                               // decrypted message text (see note above)
    val messageType: MessageType  = MessageType.TEXT,
    val direction: MessageDirection,
    val status: MessageStatus     = MessageStatus.PENDING,

    // ── Media (photos / files via IPFS) ─────────────────────────────────
    val mediaIpfsCid: String?     = null,           // IPFS content identifier
    val mediaKeyBase64: String?   = null,           // Base64(AES-256 key)
    val mediaIvBase64: String?    = null,           // Base64(GCM IV)
    val mediaMimeType: String?    = null,
    val mediaFileSizeBytes: Long? = null,
    val mediaLocalPath: String?   = null,           // path after recipient decrypts & saves

    // ── Threading ────────────────────────────────────────────────────────
    val replyToMessageId: String? = null,

    // ── Reactions (Step 15) ──────────────────────────────────────────────
    // Stored as JSON: {"👍":["GW-AAAA-BBBB"],"❤️":["GW-CCCC-DDDD"]}
    val reactionsJson: String     = "{}",

    // ── Timestamps ───────────────────────────────────────────────────────
    val timestamp: Long,
    val deliveredAt: Long?        = null,           // epoch millis
    val readAt: Long?             = null,

    // ── Disappearing messages (Step 15) ──────────────────────────────────
    val expiresAt: Long?          = null,           // epoch millis; null = never expires

    val isDeleted: Boolean        = false,          // soft-delete flag
)

enum class MessageDirection { OUTGOING, INCOMING }

enum class MessageStatus {
    PENDING,      // queued locally, not yet sent
    SENT,         // pushed to peer data channel
    DELIVERED,    // peer device acknowledged receipt
    READ,         // peer opened the conversation
    FAILED,       // all delivery retries exhausted
}

enum class MessageType {
    TEXT,
    IMAGE,
    FILE,
    CALL_RECORD,  // inline call summary card
    SYSTEM,       // e.g. "Safety number changed" banners
}
